services:
  - type: web
    name: n8n-render
    env: docker
    plan: free
    dockerImage: n8nio/n8n:latest
    autoDeploy: true
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: superclave123
      - key: N8N_HOST
        value: ${RENDER_EXTERNAL_HOSTNAME}
      - key: N8N_EDITOR_BASE_URL
        value: https://${RENDER_EXTERNAL_HOSTNAME}
      - key: WEBHOOK_URL
        value: https://${RENDER_EXTERNAL_HOSTNAME}/
      - key: DB_TYPE
        value: sqlite
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"
