services:
  - type: web
    name: n8n-render
    env: docker
    plan: free
    branch: master
    repo: https://github.com/Araxel19/n8n-render
    healthCheckPath: /
    dockerfilePath: Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: superclave123
      - key: N8N_HOST
        value: n8n-render.onrender.com
      - key: N8N_EDITOR_BASE_URL
        value: https://n8n-render.onrender.com
      - key: WEBHOOK_URL
        value: https://n8n-render.onrender.com/
      - key: DB_TYPE
        value: sqlite
